### PR TITLE
Add basic testing, CI

### PR DESCRIPTION
**Pull request by tylerjthomas9**
In reference to #1. Modified Conda.jl's tests to create a set of basic tests.

### CODE REVIEW

**Comment by cjdoris** [comment]
Thanks so much for doing this! I'll take a closer look after Christmas but from a quick scan it looks great. Happy holidays!

**Comment by tylerjthomas9** [comment]
Happy holidays! I was looking into creating a package to use micromamba from within Julia, and saw that you had already created it in a much more elegant way than I would've done.

**Comment by cjdoris** [comment]
Thanks again. The tests pass locally, so fingers crossed they pass on GitHub.

**Comment by cjdoris** [comment]
82% code coverage 👍

**Comment by tylerjthomas9** [comment]
Awesome! Glad to hear

**Pull request merged**
