### PR TITLE
Add simple access to cleaning the conda cache/index/...

### PR DESCRIPTION
**Pull request by tylerjthomas9**
Similar to Conda.jl, I think having access to cleaning the environments, without importing and manually doing the micromamba command, would be beneficial. Let me know what you think

### CODE REVIEW

**Comment by cjdoris** [comment]
Nice idea. However could you rename it to `gc`, since this package tries to follow the names from `Pkg`.

Also, I don't think it needs any arguments, just have `gc()` call `clean -y --all`. I think this is enough for most users, and power users can always call MicroMamba themselves. This is also because MicroMamba is an implementation detail - in the future we might use Conda or something else which has different cleaning options.

**Comment by tylerjthomas9** [comment]
Keeping the syntax in line with Pkg.jl is a great touch

**Comment by cjdoris** [comment]
Lovely, thanks. Will release a version in the next few days.

**Comment by cjdoris** [comment]
What would be really cool would be to integrate it into the Pkg REPL, e.g. `] conda add python` but I don't know if that's possible.

**Comment by cjdoris** [comment]
Released.

**Comment by tylerjthomas9** [comment]
Awesome!

**Pull request merged**
